// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: enrichment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение запроса
type GetEnrichmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnrichmentRequest) Reset() {
	*x = GetEnrichmentRequest{}
	mi := &file_enrichment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnrichmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrichmentRequest) ProtoMessage() {}

func (x *GetEnrichmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrichmentRequest.ProtoReflect.Descriptor instead.
func (*GetEnrichmentRequest) Descriptor() ([]byte, []int) {
	return file_enrichment_proto_rawDescGZIP(), []int{0}
}

func (x *GetEnrichmentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Сообщение ответа
type GetEnrichmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Response      string                 `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnrichmentResponse) Reset() {
	*x = GetEnrichmentResponse{}
	mi := &file_enrichment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnrichmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnrichmentResponse) ProtoMessage() {}

func (x *GetEnrichmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_enrichment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnrichmentResponse.ProtoReflect.Descriptor instead.
func (*GetEnrichmentResponse) Descriptor() ([]byte, []int) {
	return file_enrichment_proto_rawDescGZIP(), []int{1}
}

func (x *GetEnrichmentResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEnrichmentResponse) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *GetEnrichmentResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *GetEnrichmentResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetEnrichmentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_enrichment_proto protoreflect.FileDescriptor

const file_enrichment_proto_rawDesc = "" +
	"\n" +
	"\x10enrichment.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"&\n" +
	"\x14GetEnrichmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xaf\x01\n" +
	"\x15GetEnrichmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2U\n" +
	"\x11EnrichmentService\x12@\n" +
	"\rGetEnrichment\x12\x15.GetEnrichmentRequest\x1a\x16.GetEnrichmentResponse\"\x00B&Z$AIGateway/internal/transport/grpc/pbb\x06proto3"

var (
	file_enrichment_proto_rawDescOnce sync.Once
	file_enrichment_proto_rawDescData []byte
)

func file_enrichment_proto_rawDescGZIP() []byte {
	file_enrichment_proto_rawDescOnce.Do(func() {
		file_enrichment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enrichment_proto_rawDesc), len(file_enrichment_proto_rawDesc)))
	})
	return file_enrichment_proto_rawDescData
}

var file_enrichment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_enrichment_proto_goTypes = []any{
	(*GetEnrichmentRequest)(nil),  // 0: GetEnrichmentRequest
	(*GetEnrichmentResponse)(nil), // 1: GetEnrichmentResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_enrichment_proto_depIdxs = []int32{
	2, // 0: GetEnrichmentResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: EnrichmentService.GetEnrichment:input_type -> GetEnrichmentRequest
	1, // 2: EnrichmentService.GetEnrichment:output_type -> GetEnrichmentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_enrichment_proto_init() }
func file_enrichment_proto_init() {
	if File_enrichment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enrichment_proto_rawDesc), len(file_enrichment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enrichment_proto_goTypes,
		DependencyIndexes: file_enrichment_proto_depIdxs,
		MessageInfos:      file_enrichment_proto_msgTypes,
	}.Build()
	File_enrichment_proto = out.File
	file_enrichment_proto_goTypes = nil
	file_enrichment_proto_depIdxs = nil
}
