// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: enrichment.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnrichmentService_GetEnrichment_FullMethodName = "/EnrichmentService/GetEnrichment"
)

// EnrichmentServiceClient is the client API for EnrichmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис логики
type EnrichmentServiceClient interface {
	GetEnrichment(ctx context.Context, in *GetEnrichmentRequest, opts ...grpc.CallOption) (*GetEnrichmentResponse, error)
}

type enrichmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrichmentServiceClient(cc grpc.ClientConnInterface) EnrichmentServiceClient {
	return &enrichmentServiceClient{cc}
}

func (c *enrichmentServiceClient) GetEnrichment(ctx context.Context, in *GetEnrichmentRequest, opts ...grpc.CallOption) (*GetEnrichmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnrichmentResponse)
	err := c.cc.Invoke(ctx, EnrichmentService_GetEnrichment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrichmentServiceServer is the server API for EnrichmentService service.
// All implementations must embed UnimplementedEnrichmentServiceServer
// for forward compatibility.
//
// Сервис логики
type EnrichmentServiceServer interface {
	GetEnrichment(context.Context, *GetEnrichmentRequest) (*GetEnrichmentResponse, error)
	mustEmbedUnimplementedEnrichmentServiceServer()
}

// UnimplementedEnrichmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrichmentServiceServer struct{}

func (UnimplementedEnrichmentServiceServer) GetEnrichment(context.Context, *GetEnrichmentRequest) (*GetEnrichmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnrichment not implemented")
}
func (UnimplementedEnrichmentServiceServer) mustEmbedUnimplementedEnrichmentServiceServer() {}
func (UnimplementedEnrichmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeEnrichmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrichmentServiceServer will
// result in compilation errors.
type UnsafeEnrichmentServiceServer interface {
	mustEmbedUnimplementedEnrichmentServiceServer()
}

func RegisterEnrichmentServiceServer(s grpc.ServiceRegistrar, srv EnrichmentServiceServer) {
	// If the following call panics, it indicates UnimplementedEnrichmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnrichmentService_ServiceDesc, srv)
}

func _EnrichmentService_GetEnrichment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnrichmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrichmentServiceServer).GetEnrichment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrichmentService_GetEnrichment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrichmentServiceServer).GetEnrichment(ctx, req.(*GetEnrichmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnrichmentService_ServiceDesc is the grpc.ServiceDesc for EnrichmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnrichmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EnrichmentService",
	HandlerType: (*EnrichmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEnrichment",
			Handler:    _EnrichmentService_GetEnrichment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enrichment.proto",
}
